In [1]:
import torch

In [9]:
batch_size = 1
input_dim = 1
output_dim = 1
input_data = torch.rand([batch_size, input_dim], requires_grad=True)
target = torch.tensor([1.0])
print(input_data)

tensor([[0.3068]], requires_grad=True)


In [10]:
learning_rate = 1e-3
optimizer = torch.optim.Adam([input_data], lr=learning_rate)

In [19]:
# training
epochs = 100
model = torch.nn.Linear(in_features=input_dim, out_features=output_dim)
criterion = torch.nn.MSELoss()

# set model weight
model.weight.data = torch.tensor([[1.0]])
model.bias.data = torch.tensor([0.0])

# freeze the model weights
for param in model.parameters():
    param.requires_grad = False


tensor([[-0.3703]])
tensor([-0.7601])


In [17]:
for epoch in range(epochs):
    optimizer.zero_grad()

    # forward pass
    output = model(input_data)
    loss = criterion(output, target)
    
    loss.backward()

    optimizer.step()
    if epoch % 10 == 0:
        print(input_data)
    

RuntimeError: mat2 must be a matrix, got 1-D tensor