In [29]:
import torch

In [30]:
batch_size = 1
input_dim = 1
output_dim = 1
input_data = torch.rand([batch_size, input_dim], requires_grad=True)
target = torch.tensor([1.0])
print(input_data)

tensor([[0.1213]], requires_grad=True)


In [31]:
learning_rate = 1e-1
optimizer = torch.optim.Adam([input_data], lr=learning_rate)

In [32]:
# training
epochs = 100
model = torch.nn.Linear(in_features=input_dim, out_features=output_dim)
criterion = torch.nn.MSELoss()

# set model weight
model.weight.data = torch.tensor([[1.0]])
model.bias.data = torch.tensor([0.0])

# freeze the model weights
for param in model.parameters():
    param.requires_grad = False


In [33]:
for epoch in range(epochs):
    optimizer.zero_grad()

    # forward pass
    output = model(input_data)
    loss = criterion(output, target)
    
    loss.backward()

    optimizer.step()
    if epoch % 10 == 0:
        print(input_data)
    

tensor([[0.2213]], requires_grad=True)
tensor([[1.0864]], requires_grad=True)
tensor([[1.2144]], requires_grad=True)
tensor([[0.9358]], requires_grad=True)
tensor([[0.9386]], requires_grad=True)
tensor([[1.0449]], requires_grad=True)
tensor([[1.0005]], requires_grad=True)
tensor([[0.9842]], requires_grad=True)
tensor([[1.0100]], requires_grad=True)
tensor([[0.9982]], requires_grad=True)


/Users/emilryd/anaconda3/envs/neuralhydrology/lib/python3.10/site-packages/torch/nn/modules/loss.py:538: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [34]:
input_data

tensor([[0.9971]], requires_grad=True)

In [35]:
model.weight.data

tensor([[1.]])

In [28]:
model.bias.data

tensor([0.])